
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.officiallysp.woodworks.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import com.officiallysp.woodworks.block.RubberWoodBlock;
import com.officiallysp.woodworks.block.RubberStairsBlock;
import com.officiallysp.woodworks.block.RubberSlabBlock;
import com.officiallysp.woodworks.block.RubberPressurePlateBlock;
import com.officiallysp.woodworks.block.RubberPlanksBlock;
import com.officiallysp.woodworks.block.RubberLogBlock;
import com.officiallysp.woodworks.block.RubberLeavesBlock;
import com.officiallysp.woodworks.block.RubberFenceGateBlock;
import com.officiallysp.woodworks.block.RubberFenceBlock;
import com.officiallysp.woodworks.block.RubberButtonBlock;
import com.officiallysp.woodworks.block.PineWoodBlock;
import com.officiallysp.woodworks.block.PineStairsBlock;
import com.officiallysp.woodworks.block.PineSlabBlock;
import com.officiallysp.woodworks.block.PinePressurePlateBlock;
import com.officiallysp.woodworks.block.PinePlanksBlock;
import com.officiallysp.woodworks.block.PineLogBlock;
import com.officiallysp.woodworks.block.PineLeavesBlock;
import com.officiallysp.woodworks.block.PineFenceGateBlock;
import com.officiallysp.woodworks.block.PineFenceBlock;
import com.officiallysp.woodworks.block.PineButtonBlock;
import com.officiallysp.woodworks.block.PalmWoodBlock;
import com.officiallysp.woodworks.block.PalmStairsBlock;
import com.officiallysp.woodworks.block.PalmSlabBlock;
import com.officiallysp.woodworks.block.PalmPressurePlateBlock;
import com.officiallysp.woodworks.block.PalmPlanksBlock;
import com.officiallysp.woodworks.block.PalmLogBlock;
import com.officiallysp.woodworks.block.PalmLeavesBlock;
import com.officiallysp.woodworks.block.PalmFenceGateBlock;
import com.officiallysp.woodworks.block.PalmFenceBlock;
import com.officiallysp.woodworks.block.PalmButtonBlock;
import com.officiallysp.woodworks.block.MapleWoodBlock;
import com.officiallysp.woodworks.block.MapleStairsBlock;
import com.officiallysp.woodworks.block.MapleSlabBlock;
import com.officiallysp.woodworks.block.MaplePressurePlateBlock;
import com.officiallysp.woodworks.block.MaplePlanksBlock;
import com.officiallysp.woodworks.block.MapleLogBlock;
import com.officiallysp.woodworks.block.MapleLeavesBlock;
import com.officiallysp.woodworks.block.MapleFenceGateBlock;
import com.officiallysp.woodworks.block.MapleFenceBlock;
import com.officiallysp.woodworks.block.MapleButtonBlock;
import com.officiallysp.woodworks.block.MangoWoodBlock;
import com.officiallysp.woodworks.block.MangoStairsBlock;
import com.officiallysp.woodworks.block.MangoSlabBlock;
import com.officiallysp.woodworks.block.MangoPressurePlateBlock;
import com.officiallysp.woodworks.block.MangoPlanksBlock;
import com.officiallysp.woodworks.block.MangoLogBlock;
import com.officiallysp.woodworks.block.MangoLeavesBlock;
import com.officiallysp.woodworks.block.MangoFenceGateBlock;
import com.officiallysp.woodworks.block.MangoFenceBlock;
import com.officiallysp.woodworks.block.MangoButtonBlock;
import com.officiallysp.woodworks.block.CedarWoodBlock;
import com.officiallysp.woodworks.block.CedarStairsBlock;
import com.officiallysp.woodworks.block.CedarSlabBlock;
import com.officiallysp.woodworks.block.CedarPressurePlateBlock;
import com.officiallysp.woodworks.block.CedarPlanksBlock;
import com.officiallysp.woodworks.block.CedarLogBlock;
import com.officiallysp.woodworks.block.CedarLeavesBlock;
import com.officiallysp.woodworks.block.CedarFenceGateBlock;
import com.officiallysp.woodworks.block.CedarFenceBlock;
import com.officiallysp.woodworks.block.CedarButtonBlock;
import com.officiallysp.woodworks.WoodworksMod;

public class WoodworksModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, WoodworksMod.MODID);
	public static final RegistryObject<Block> MAPLE_LOG = REGISTRY.register("maple_log", () -> new MapleLogBlock());
	public static final RegistryObject<Block> MAPLE_WOOD = REGISTRY.register("maple_wood", () -> new MapleWoodBlock());
	public static final RegistryObject<Block> MAPLE_PLANKS = REGISTRY.register("maple_planks", () -> new MaplePlanksBlock());
	public static final RegistryObject<Block> MAPLE_LEAVES = REGISTRY.register("maple_leaves", () -> new MapleLeavesBlock());
	public static final RegistryObject<Block> MAPLE_STAIRS = REGISTRY.register("maple_stairs", () -> new MapleStairsBlock());
	public static final RegistryObject<Block> MAPLE_SLAB = REGISTRY.register("maple_slab", () -> new MapleSlabBlock());
	public static final RegistryObject<Block> MAPLE_FENCE = REGISTRY.register("maple_fence", () -> new MapleFenceBlock());
	public static final RegistryObject<Block> MAPLE_FENCE_GATE = REGISTRY.register("maple_fence_gate", () -> new MapleFenceGateBlock());
	public static final RegistryObject<Block> MAPLE_PRESSURE_PLATE = REGISTRY.register("maple_pressure_plate", () -> new MaplePressurePlateBlock());
	public static final RegistryObject<Block> MAPLE_BUTTON = REGISTRY.register("maple_button", () -> new MapleButtonBlock());
	public static final RegistryObject<Block> PINE_WOOD = REGISTRY.register("pine_wood", () -> new PineWoodBlock());
	public static final RegistryObject<Block> PINE_LOG = REGISTRY.register("pine_log", () -> new PineLogBlock());
	public static final RegistryObject<Block> PINE_PLANKS = REGISTRY.register("pine_planks", () -> new PinePlanksBlock());
	public static final RegistryObject<Block> PINE_LEAVES = REGISTRY.register("pine_leaves", () -> new PineLeavesBlock());
	public static final RegistryObject<Block> PINE_STAIRS = REGISTRY.register("pine_stairs", () -> new PineStairsBlock());
	public static final RegistryObject<Block> PINE_SLAB = REGISTRY.register("pine_slab", () -> new PineSlabBlock());
	public static final RegistryObject<Block> PINE_FENCE = REGISTRY.register("pine_fence", () -> new PineFenceBlock());
	public static final RegistryObject<Block> PINE_FENCE_GATE = REGISTRY.register("pine_fence_gate", () -> new PineFenceGateBlock());
	public static final RegistryObject<Block> PINE_PRESSURE_PLATE = REGISTRY.register("pine_pressure_plate", () -> new PinePressurePlateBlock());
	public static final RegistryObject<Block> PINE_BUTTON = REGISTRY.register("pine_button", () -> new PineButtonBlock());
	public static final RegistryObject<Block> CEDAR_WOOD = REGISTRY.register("cedar_wood", () -> new CedarWoodBlock());
	public static final RegistryObject<Block> CEDAR_LOG = REGISTRY.register("cedar_log", () -> new CedarLogBlock());
	public static final RegistryObject<Block> CEDAR_PLANKS = REGISTRY.register("cedar_planks", () -> new CedarPlanksBlock());
	public static final RegistryObject<Block> CEDAR_LEAVES = REGISTRY.register("cedar_leaves", () -> new CedarLeavesBlock());
	public static final RegistryObject<Block> CEDAR_STAIRS = REGISTRY.register("cedar_stairs", () -> new CedarStairsBlock());
	public static final RegistryObject<Block> CEDAR_SLAB = REGISTRY.register("cedar_slab", () -> new CedarSlabBlock());
	public static final RegistryObject<Block> CEDAR_FENCE = REGISTRY.register("cedar_fence", () -> new CedarFenceBlock());
	public static final RegistryObject<Block> CEDAR_FENCE_GATE = REGISTRY.register("cedar_fence_gate", () -> new CedarFenceGateBlock());
	public static final RegistryObject<Block> CEDAR_PRESSURE_PLATE = REGISTRY.register("cedar_pressure_plate", () -> new CedarPressurePlateBlock());
	public static final RegistryObject<Block> CEDAR_BUTTON = REGISTRY.register("cedar_button", () -> new CedarButtonBlock());
	public static final RegistryObject<Block> PALM_WOOD = REGISTRY.register("palm_wood", () -> new PalmWoodBlock());
	public static final RegistryObject<Block> PALM_LOG = REGISTRY.register("palm_log", () -> new PalmLogBlock());
	public static final RegistryObject<Block> PALM_PLANKS = REGISTRY.register("palm_planks", () -> new PalmPlanksBlock());
	public static final RegistryObject<Block> PALM_LEAVES = REGISTRY.register("palm_leaves", () -> new PalmLeavesBlock());
	public static final RegistryObject<Block> PALM_STAIRS = REGISTRY.register("palm_stairs", () -> new PalmStairsBlock());
	public static final RegistryObject<Block> PALM_SLAB = REGISTRY.register("palm_slab", () -> new PalmSlabBlock());
	public static final RegistryObject<Block> PALM_FENCE = REGISTRY.register("palm_fence", () -> new PalmFenceBlock());
	public static final RegistryObject<Block> PALM_FENCE_GATE = REGISTRY.register("palm_fence_gate", () -> new PalmFenceGateBlock());
	public static final RegistryObject<Block> PALM_PRESSURE_PLATE = REGISTRY.register("palm_pressure_plate", () -> new PalmPressurePlateBlock());
	public static final RegistryObject<Block> PALM_BUTTON = REGISTRY.register("palm_button", () -> new PalmButtonBlock());
	public static final RegistryObject<Block> MANGO_WOOD = REGISTRY.register("mango_wood", () -> new MangoWoodBlock());
	public static final RegistryObject<Block> MANGO_LOG = REGISTRY.register("mango_log", () -> new MangoLogBlock());
	public static final RegistryObject<Block> MANGO_PLANKS = REGISTRY.register("mango_planks", () -> new MangoPlanksBlock());
	public static final RegistryObject<Block> MANGO_LEAVES = REGISTRY.register("mango_leaves", () -> new MangoLeavesBlock());
	public static final RegistryObject<Block> MANGO_STAIRS = REGISTRY.register("mango_stairs", () -> new MangoStairsBlock());
	public static final RegistryObject<Block> MANGO_SLAB = REGISTRY.register("mango_slab", () -> new MangoSlabBlock());
	public static final RegistryObject<Block> MANGO_FENCE = REGISTRY.register("mango_fence", () -> new MangoFenceBlock());
	public static final RegistryObject<Block> MANGO_FENCE_GATE = REGISTRY.register("mango_fence_gate", () -> new MangoFenceGateBlock());
	public static final RegistryObject<Block> MANGO_PRESSURE_PLATE = REGISTRY.register("mango_pressure_plate", () -> new MangoPressurePlateBlock());
	public static final RegistryObject<Block> MANGO_BUTTON = REGISTRY.register("mango_button", () -> new MangoButtonBlock());
	public static final RegistryObject<Block> RUBBER_WOOD = REGISTRY.register("rubber_wood", () -> new RubberWoodBlock());
	public static final RegistryObject<Block> RUBBER_LOG = REGISTRY.register("rubber_log", () -> new RubberLogBlock());
	public static final RegistryObject<Block> RUBBER_PLANKS = REGISTRY.register("rubber_planks", () -> new RubberPlanksBlock());
	public static final RegistryObject<Block> RUBBER_LEAVES = REGISTRY.register("rubber_leaves", () -> new RubberLeavesBlock());
	public static final RegistryObject<Block> RUBBER_STAIRS = REGISTRY.register("rubber_stairs", () -> new RubberStairsBlock());
	public static final RegistryObject<Block> RUBBER_SLAB = REGISTRY.register("rubber_slab", () -> new RubberSlabBlock());
	public static final RegistryObject<Block> RUBBER_FENCE = REGISTRY.register("rubber_fence", () -> new RubberFenceBlock());
	public static final RegistryObject<Block> RUBBER_FENCE_GATE = REGISTRY.register("rubber_fence_gate", () -> new RubberFenceGateBlock());
	public static final RegistryObject<Block> RUBBER_PRESSURE_PLATE = REGISTRY.register("rubber_pressure_plate", () -> new RubberPressurePlateBlock());
	public static final RegistryObject<Block> RUBBER_BUTTON = REGISTRY.register("rubber_button", () -> new RubberButtonBlock());
}
