
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.officiallysp.woodworks.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import com.officiallysp.woodworks.block.WoodworkerBlock;
import com.officiallysp.woodworks.block.WillowWoodBlock;
import com.officiallysp.woodworks.block.WillowStairsBlock;
import com.officiallysp.woodworks.block.WillowSlabBlock;
import com.officiallysp.woodworks.block.WillowPressurePlateBlock;
import com.officiallysp.woodworks.block.WillowPlanksBlock;
import com.officiallysp.woodworks.block.WillowLogBlock;
import com.officiallysp.woodworks.block.WillowLeavesBlock;
import com.officiallysp.woodworks.block.WillowFenceGateBlock;
import com.officiallysp.woodworks.block.WillowFenceBlock;
import com.officiallysp.woodworks.block.WillowButtonBlock;
import com.officiallysp.woodworks.block.TeakWoodBlock;
import com.officiallysp.woodworks.block.TeakStairsBlock;
import com.officiallysp.woodworks.block.TeakSlabBlock;
import com.officiallysp.woodworks.block.TeakPressurePlateBlock;
import com.officiallysp.woodworks.block.TeakPlanksBlock;
import com.officiallysp.woodworks.block.TeakLogBlock;
import com.officiallysp.woodworks.block.TeakLeavesBlock;
import com.officiallysp.woodworks.block.TeakFenceGateBlock;
import com.officiallysp.woodworks.block.TeakFenceBlock;
import com.officiallysp.woodworks.block.TeakButtonBlock;
import com.officiallysp.woodworks.block.StrippedWillowWoodBlock;
import com.officiallysp.woodworks.block.StrippedWillowLogBlock;
import com.officiallysp.woodworks.block.RubberWoodBlock;
import com.officiallysp.woodworks.block.RubberStairsBlock;
import com.officiallysp.woodworks.block.RubberSlabBlock;
import com.officiallysp.woodworks.block.RubberPressurePlateBlock;
import com.officiallysp.woodworks.block.RubberPlanksBlock;
import com.officiallysp.woodworks.block.RubberLogBlock;
import com.officiallysp.woodworks.block.RubberLeavesBlock;
import com.officiallysp.woodworks.block.RubberFenceGateBlock;
import com.officiallysp.woodworks.block.RubberFenceBlock;
import com.officiallysp.woodworks.block.RubberButtonBlock;
import com.officiallysp.woodworks.block.PineWoodBlock;
import com.officiallysp.woodworks.block.PineStairsBlock;
import com.officiallysp.woodworks.block.PineSlabBlock;
import com.officiallysp.woodworks.block.PinePressurePlateBlock;
import com.officiallysp.woodworks.block.PinePlanksBlock;
import com.officiallysp.woodworks.block.PineLogBlock;
import com.officiallysp.woodworks.block.PineLeavesBlock;
import com.officiallysp.woodworks.block.PineFenceGateBlock;
import com.officiallysp.woodworks.block.PineFenceBlock;
import com.officiallysp.woodworks.block.PineButtonBlock;
import com.officiallysp.woodworks.block.PalmWoodBlock;
import com.officiallysp.woodworks.block.PalmStairsBlock;
import com.officiallysp.woodworks.block.PalmSlabBlock;
import com.officiallysp.woodworks.block.PalmPressurePlateBlock;
import com.officiallysp.woodworks.block.PalmPlanksBlock;
import com.officiallysp.woodworks.block.PalmLogBlock;
import com.officiallysp.woodworks.block.PalmLeavesBlock;
import com.officiallysp.woodworks.block.PalmFenceGateBlock;
import com.officiallysp.woodworks.block.PalmFenceBlock;
import com.officiallysp.woodworks.block.PalmButtonBlock;
import com.officiallysp.woodworks.block.MapleWoodBlock;
import com.officiallysp.woodworks.block.MapleStairsBlock;
import com.officiallysp.woodworks.block.MapleSlabBlock;
import com.officiallysp.woodworks.block.MaplePressurePlateBlock;
import com.officiallysp.woodworks.block.MaplePlanksBlock;
import com.officiallysp.woodworks.block.MapleLogBlock;
import com.officiallysp.woodworks.block.MapleLeavesBlock;
import com.officiallysp.woodworks.block.MapleFenceGateBlock;
import com.officiallysp.woodworks.block.MapleFenceBlock;
import com.officiallysp.woodworks.block.MapleFallLeavesBlock;
import com.officiallysp.woodworks.block.MapleButtonBlock;
import com.officiallysp.woodworks.block.MangoWoodBlock;
import com.officiallysp.woodworks.block.MangoStairsBlock;
import com.officiallysp.woodworks.block.MangoSlabBlock;
import com.officiallysp.woodworks.block.MangoPressurePlateBlock;
import com.officiallysp.woodworks.block.MangoPlanksBlock;
import com.officiallysp.woodworks.block.MangoLogBlock;
import com.officiallysp.woodworks.block.MangoLeavesBlock;
import com.officiallysp.woodworks.block.MangoFenceGateBlock;
import com.officiallysp.woodworks.block.MangoFenceBlock;
import com.officiallysp.woodworks.block.MangoButtonBlock;
import com.officiallysp.woodworks.block.MahoganyWoodBlock;
import com.officiallysp.woodworks.block.MahoganyStairsBlock;
import com.officiallysp.woodworks.block.MahoganySlabBlock;
import com.officiallysp.woodworks.block.MahoganyPressurePlateBlock;
import com.officiallysp.woodworks.block.MahoganyPlanksBlock;
import com.officiallysp.woodworks.block.MahoganyLogBlock;
import com.officiallysp.woodworks.block.MahoganyLeavesBlock;
import com.officiallysp.woodworks.block.MahoganyFenceGateBlock;
import com.officiallysp.woodworks.block.MahoganyFenceBlock;
import com.officiallysp.woodworks.block.MahoganyButtonBlock;
import com.officiallysp.woodworks.block.KapokWoodBlock;
import com.officiallysp.woodworks.block.KapokStairsBlock;
import com.officiallysp.woodworks.block.KapokSlabBlock;
import com.officiallysp.woodworks.block.KapokPressurePlateBlock;
import com.officiallysp.woodworks.block.KapokPlanksBlock;
import com.officiallysp.woodworks.block.KapokLogBlock;
import com.officiallysp.woodworks.block.KapokLeavesBlock;
import com.officiallysp.woodworks.block.KapokFenceGateBlock;
import com.officiallysp.woodworks.block.KapokFenceBlock;
import com.officiallysp.woodworks.block.KapokButtonBlock;
import com.officiallysp.woodworks.block.JoshuaWoodBlock;
import com.officiallysp.woodworks.block.JoshuaStairsBlock;
import com.officiallysp.woodworks.block.JoshuaSlabBlock;
import com.officiallysp.woodworks.block.JoshuaPressurePlateBlock;
import com.officiallysp.woodworks.block.JoshuaPlanksBlock;
import com.officiallysp.woodworks.block.JoshuaLogBlock;
import com.officiallysp.woodworks.block.JoshuaLeavesBlock;
import com.officiallysp.woodworks.block.JoshuaFenceGateBlock;
import com.officiallysp.woodworks.block.JoshuaFenceBlock;
import com.officiallysp.woodworks.block.JoshuaButtonBlock;
import com.officiallysp.woodworks.block.CedarWoodBlock;
import com.officiallysp.woodworks.block.CedarStairsBlock;
import com.officiallysp.woodworks.block.CedarSlabBlock;
import com.officiallysp.woodworks.block.CedarPressurePlateBlock;
import com.officiallysp.woodworks.block.CedarPlanksBlock;
import com.officiallysp.woodworks.block.CedarLogBlock;
import com.officiallysp.woodworks.block.CedarLeavesBlock;
import com.officiallysp.woodworks.block.CedarFenceGateBlock;
import com.officiallysp.woodworks.block.CedarFenceBlock;
import com.officiallysp.woodworks.block.CedarButtonBlock;
import com.officiallysp.woodworks.block.CactusWoodBlock;
import com.officiallysp.woodworks.block.CactusStairsBlock;
import com.officiallysp.woodworks.block.CactusSlabBlock;
import com.officiallysp.woodworks.block.CactusPressurePlateBlock;
import com.officiallysp.woodworks.block.CactusPlanksBlock;
import com.officiallysp.woodworks.block.CactusLogBlock;
import com.officiallysp.woodworks.block.CactusLeavesBlock;
import com.officiallysp.woodworks.block.CactusFenceGateBlock;
import com.officiallysp.woodworks.block.CactusFenceBlock;
import com.officiallysp.woodworks.block.CactusButtonBlock;
import com.officiallysp.woodworks.block.BeechWoodBlock;
import com.officiallysp.woodworks.block.BeechStairsBlock;
import com.officiallysp.woodworks.block.BeechSlabBlock;
import com.officiallysp.woodworks.block.BeechPressurePlateBlock;
import com.officiallysp.woodworks.block.BeechPlanksBlock;
import com.officiallysp.woodworks.block.BeechLogBlock;
import com.officiallysp.woodworks.block.BeechLeavesBlock;
import com.officiallysp.woodworks.block.BeechFenceGateBlock;
import com.officiallysp.woodworks.block.BeechFenceBlock;
import com.officiallysp.woodworks.block.BeechFallLeavesBlock;
import com.officiallysp.woodworks.block.BeechButtonBlock;
import com.officiallysp.woodworks.block.BaobabWoodBlock;
import com.officiallysp.woodworks.block.BaobabStairsBlock;
import com.officiallysp.woodworks.block.BaobabSlabBlock;
import com.officiallysp.woodworks.block.BaobabPressurePlateBlock;
import com.officiallysp.woodworks.block.BaobabPlanksBlock;
import com.officiallysp.woodworks.block.BaobabLogBlock;
import com.officiallysp.woodworks.block.BaobabLeavesBlock;
import com.officiallysp.woodworks.block.BaobabFenceGateBlock;
import com.officiallysp.woodworks.block.BaobabFenceBlock;
import com.officiallysp.woodworks.block.BaobabButtonBlock;
import com.officiallysp.woodworks.block.AspenWoodBlock;
import com.officiallysp.woodworks.block.AspenStairsBlock;
import com.officiallysp.woodworks.block.AspenSlabBlock;
import com.officiallysp.woodworks.block.AspenPressurePlateBlock;
import com.officiallysp.woodworks.block.AspenPlanksBlock;
import com.officiallysp.woodworks.block.AspenLogBlock;
import com.officiallysp.woodworks.block.AspenLeavesBlock;
import com.officiallysp.woodworks.block.AspenFenceGateBlock;
import com.officiallysp.woodworks.block.AspenFenceBlock;
import com.officiallysp.woodworks.block.AspenFallLeavesBlock;
import com.officiallysp.woodworks.block.AspenButtonBlock;
import com.officiallysp.woodworks.WoodworksMod;

public class WoodworksModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, WoodworksMod.MODID);
	public static final RegistryObject<Block> MAPLE_LOG = REGISTRY.register("maple_log", () -> new MapleLogBlock());
	public static final RegistryObject<Block> MAPLE_WOOD = REGISTRY.register("maple_wood", () -> new MapleWoodBlock());
	public static final RegistryObject<Block> MAPLE_PLANKS = REGISTRY.register("maple_planks", () -> new MaplePlanksBlock());
	public static final RegistryObject<Block> MAPLE_STAIRS = REGISTRY.register("maple_stairs", () -> new MapleStairsBlock());
	public static final RegistryObject<Block> MAPLE_SLAB = REGISTRY.register("maple_slab", () -> new MapleSlabBlock());
	public static final RegistryObject<Block> MAPLE_FENCE = REGISTRY.register("maple_fence", () -> new MapleFenceBlock());
	public static final RegistryObject<Block> MAPLE_FENCE_GATE = REGISTRY.register("maple_fence_gate", () -> new MapleFenceGateBlock());
	public static final RegistryObject<Block> MAPLE_PRESSURE_PLATE = REGISTRY.register("maple_pressure_plate", () -> new MaplePressurePlateBlock());
	public static final RegistryObject<Block> MAPLE_BUTTON = REGISTRY.register("maple_button", () -> new MapleButtonBlock());
	public static final RegistryObject<Block> PINE_WOOD = REGISTRY.register("pine_wood", () -> new PineWoodBlock());
	public static final RegistryObject<Block> PINE_LOG = REGISTRY.register("pine_log", () -> new PineLogBlock());
	public static final RegistryObject<Block> PINE_PLANKS = REGISTRY.register("pine_planks", () -> new PinePlanksBlock());
	public static final RegistryObject<Block> PINE_STAIRS = REGISTRY.register("pine_stairs", () -> new PineStairsBlock());
	public static final RegistryObject<Block> PINE_SLAB = REGISTRY.register("pine_slab", () -> new PineSlabBlock());
	public static final RegistryObject<Block> PINE_FENCE = REGISTRY.register("pine_fence", () -> new PineFenceBlock());
	public static final RegistryObject<Block> PINE_FENCE_GATE = REGISTRY.register("pine_fence_gate", () -> new PineFenceGateBlock());
	public static final RegistryObject<Block> PINE_PRESSURE_PLATE = REGISTRY.register("pine_pressure_plate", () -> new PinePressurePlateBlock());
	public static final RegistryObject<Block> PINE_BUTTON = REGISTRY.register("pine_button", () -> new PineButtonBlock());
	public static final RegistryObject<Block> CEDAR_WOOD = REGISTRY.register("cedar_wood", () -> new CedarWoodBlock());
	public static final RegistryObject<Block> CEDAR_LOG = REGISTRY.register("cedar_log", () -> new CedarLogBlock());
	public static final RegistryObject<Block> CEDAR_PLANKS = REGISTRY.register("cedar_planks", () -> new CedarPlanksBlock());
	public static final RegistryObject<Block> CEDAR_STAIRS = REGISTRY.register("cedar_stairs", () -> new CedarStairsBlock());
	public static final RegistryObject<Block> CEDAR_SLAB = REGISTRY.register("cedar_slab", () -> new CedarSlabBlock());
	public static final RegistryObject<Block> CEDAR_FENCE = REGISTRY.register("cedar_fence", () -> new CedarFenceBlock());
	public static final RegistryObject<Block> CEDAR_FENCE_GATE = REGISTRY.register("cedar_fence_gate", () -> new CedarFenceGateBlock());
	public static final RegistryObject<Block> CEDAR_PRESSURE_PLATE = REGISTRY.register("cedar_pressure_plate", () -> new CedarPressurePlateBlock());
	public static final RegistryObject<Block> CEDAR_BUTTON = REGISTRY.register("cedar_button", () -> new CedarButtonBlock());
	public static final RegistryObject<Block> PALM_WOOD = REGISTRY.register("palm_wood", () -> new PalmWoodBlock());
	public static final RegistryObject<Block> PALM_LOG = REGISTRY.register("palm_log", () -> new PalmLogBlock());
	public static final RegistryObject<Block> PALM_PLANKS = REGISTRY.register("palm_planks", () -> new PalmPlanksBlock());
	public static final RegistryObject<Block> PALM_STAIRS = REGISTRY.register("palm_stairs", () -> new PalmStairsBlock());
	public static final RegistryObject<Block> PALM_SLAB = REGISTRY.register("palm_slab", () -> new PalmSlabBlock());
	public static final RegistryObject<Block> PALM_FENCE = REGISTRY.register("palm_fence", () -> new PalmFenceBlock());
	public static final RegistryObject<Block> PALM_FENCE_GATE = REGISTRY.register("palm_fence_gate", () -> new PalmFenceGateBlock());
	public static final RegistryObject<Block> PALM_PRESSURE_PLATE = REGISTRY.register("palm_pressure_plate", () -> new PalmPressurePlateBlock());
	public static final RegistryObject<Block> PALM_BUTTON = REGISTRY.register("palm_button", () -> new PalmButtonBlock());
	public static final RegistryObject<Block> MANGO_WOOD = REGISTRY.register("mango_wood", () -> new MangoWoodBlock());
	public static final RegistryObject<Block> MANGO_LOG = REGISTRY.register("mango_log", () -> new MangoLogBlock());
	public static final RegistryObject<Block> MANGO_PLANKS = REGISTRY.register("mango_planks", () -> new MangoPlanksBlock());
	public static final RegistryObject<Block> MANGO_STAIRS = REGISTRY.register("mango_stairs", () -> new MangoStairsBlock());
	public static final RegistryObject<Block> MANGO_SLAB = REGISTRY.register("mango_slab", () -> new MangoSlabBlock());
	public static final RegistryObject<Block> MANGO_FENCE = REGISTRY.register("mango_fence", () -> new MangoFenceBlock());
	public static final RegistryObject<Block> MANGO_FENCE_GATE = REGISTRY.register("mango_fence_gate", () -> new MangoFenceGateBlock());
	public static final RegistryObject<Block> MANGO_PRESSURE_PLATE = REGISTRY.register("mango_pressure_plate", () -> new MangoPressurePlateBlock());
	public static final RegistryObject<Block> MANGO_BUTTON = REGISTRY.register("mango_button", () -> new MangoButtonBlock());
	public static final RegistryObject<Block> RUBBER_WOOD = REGISTRY.register("rubber_wood", () -> new RubberWoodBlock());
	public static final RegistryObject<Block> RUBBER_LOG = REGISTRY.register("rubber_log", () -> new RubberLogBlock());
	public static final RegistryObject<Block> RUBBER_PLANKS = REGISTRY.register("rubber_planks", () -> new RubberPlanksBlock());
	public static final RegistryObject<Block> RUBBER_STAIRS = REGISTRY.register("rubber_stairs", () -> new RubberStairsBlock());
	public static final RegistryObject<Block> RUBBER_SLAB = REGISTRY.register("rubber_slab", () -> new RubberSlabBlock());
	public static final RegistryObject<Block> RUBBER_FENCE = REGISTRY.register("rubber_fence", () -> new RubberFenceBlock());
	public static final RegistryObject<Block> RUBBER_FENCE_GATE = REGISTRY.register("rubber_fence_gate", () -> new RubberFenceGateBlock());
	public static final RegistryObject<Block> RUBBER_PRESSURE_PLATE = REGISTRY.register("rubber_pressure_plate", () -> new RubberPressurePlateBlock());
	public static final RegistryObject<Block> RUBBER_BUTTON = REGISTRY.register("rubber_button", () -> new RubberButtonBlock());
	public static final RegistryObject<Block> BEECH_WOOD = REGISTRY.register("beech_wood", () -> new BeechWoodBlock());
	public static final RegistryObject<Block> BEECH_LOG = REGISTRY.register("beech_log", () -> new BeechLogBlock());
	public static final RegistryObject<Block> BEECH_PLANKS = REGISTRY.register("beech_planks", () -> new BeechPlanksBlock());
	public static final RegistryObject<Block> BEECH_STAIRS = REGISTRY.register("beech_stairs", () -> new BeechStairsBlock());
	public static final RegistryObject<Block> BEECH_SLAB = REGISTRY.register("beech_slab", () -> new BeechSlabBlock());
	public static final RegistryObject<Block> BEECH_FENCE = REGISTRY.register("beech_fence", () -> new BeechFenceBlock());
	public static final RegistryObject<Block> BEECH_FENCE_GATE = REGISTRY.register("beech_fence_gate", () -> new BeechFenceGateBlock());
	public static final RegistryObject<Block> BEECH_PRESSURE_PLATE = REGISTRY.register("beech_pressure_plate", () -> new BeechPressurePlateBlock());
	public static final RegistryObject<Block> BEECH_BUTTON = REGISTRY.register("beech_button", () -> new BeechButtonBlock());
	public static final RegistryObject<Block> WILLOW_WOOD = REGISTRY.register("willow_wood", () -> new WillowWoodBlock());
	public static final RegistryObject<Block> STRIPPED_WILLOW_WOOD = REGISTRY.register("stripped_willow_wood", () -> new StrippedWillowWoodBlock());
	public static final RegistryObject<Block> WILLOW_LOG = REGISTRY.register("willow_log", () -> new WillowLogBlock());
	public static final RegistryObject<Block> STRIPPED_WILLOW_LOG = REGISTRY.register("stripped_willow_log", () -> new StrippedWillowLogBlock());
	public static final RegistryObject<Block> WILLOW_PLANKS = REGISTRY.register("willow_planks", () -> new WillowPlanksBlock());
	public static final RegistryObject<Block> WILLOW_STAIRS = REGISTRY.register("willow_stairs", () -> new WillowStairsBlock());
	public static final RegistryObject<Block> WILLOW_SLAB = REGISTRY.register("willow_slab", () -> new WillowSlabBlock());
	public static final RegistryObject<Block> WILLOW_FENCE = REGISTRY.register("willow_fence", () -> new WillowFenceBlock());
	public static final RegistryObject<Block> WILLOW_FENCE_GATE = REGISTRY.register("willow_fence_gate", () -> new WillowFenceGateBlock());
	public static final RegistryObject<Block> WILLOW_PRESSURE_PLATE = REGISTRY.register("willow_pressure_plate", () -> new WillowPressurePlateBlock());
	public static final RegistryObject<Block> WILLOW_BUTTON = REGISTRY.register("willow_button", () -> new WillowButtonBlock());
	public static final RegistryObject<Block> ASPEN_WOOD = REGISTRY.register("aspen_wood", () -> new AspenWoodBlock());
	public static final RegistryObject<Block> ASPEN_LOG = REGISTRY.register("aspen_log", () -> new AspenLogBlock());
	public static final RegistryObject<Block> ASPEN_PLANKS = REGISTRY.register("aspen_planks", () -> new AspenPlanksBlock());
	public static final RegistryObject<Block> ASPEN_STAIRS = REGISTRY.register("aspen_stairs", () -> new AspenStairsBlock());
	public static final RegistryObject<Block> ASPEN_SLAB = REGISTRY.register("aspen_slab", () -> new AspenSlabBlock());
	public static final RegistryObject<Block> ASPEN_FENCE = REGISTRY.register("aspen_fence", () -> new AspenFenceBlock());
	public static final RegistryObject<Block> ASPEN_FENCE_GATE = REGISTRY.register("aspen_fence_gate", () -> new AspenFenceGateBlock());
	public static final RegistryObject<Block> ASPEN_PRESSURE_PLATE = REGISTRY.register("aspen_pressure_plate", () -> new AspenPressurePlateBlock());
	public static final RegistryObject<Block> ASPEN_BUTTON = REGISTRY.register("aspen_button", () -> new AspenButtonBlock());
	public static final RegistryObject<Block> JOSHUA_WOOD = REGISTRY.register("joshua_wood", () -> new JoshuaWoodBlock());
	public static final RegistryObject<Block> JOSHUA_LOG = REGISTRY.register("joshua_log", () -> new JoshuaLogBlock());
	public static final RegistryObject<Block> JOSHUA_PLANKS = REGISTRY.register("joshua_planks", () -> new JoshuaPlanksBlock());
	public static final RegistryObject<Block> JOSHUA_STAIRS = REGISTRY.register("joshua_stairs", () -> new JoshuaStairsBlock());
	public static final RegistryObject<Block> JOSHUA_SLAB = REGISTRY.register("joshua_slab", () -> new JoshuaSlabBlock());
	public static final RegistryObject<Block> JOSHUA_FENCE = REGISTRY.register("joshua_fence", () -> new JoshuaFenceBlock());
	public static final RegistryObject<Block> JOSHUA_FENCE_GATE = REGISTRY.register("joshua_fence_gate", () -> new JoshuaFenceGateBlock());
	public static final RegistryObject<Block> JOSHUA_PRESSURE_PLATE = REGISTRY.register("joshua_pressure_plate", () -> new JoshuaPressurePlateBlock());
	public static final RegistryObject<Block> JOSHUA_BUTTON = REGISTRY.register("joshua_button", () -> new JoshuaButtonBlock());
	public static final RegistryObject<Block> BAOBAB_WOOD = REGISTRY.register("baobab_wood", () -> new BaobabWoodBlock());
	public static final RegistryObject<Block> BAOBAB_LOG = REGISTRY.register("baobab_log", () -> new BaobabLogBlock());
	public static final RegistryObject<Block> BAOBAB_PLANKS = REGISTRY.register("baobab_planks", () -> new BaobabPlanksBlock());
	public static final RegistryObject<Block> BAOBAB_STAIRS = REGISTRY.register("baobab_stairs", () -> new BaobabStairsBlock());
	public static final RegistryObject<Block> BAOBAB_SLAB = REGISTRY.register("baobab_slab", () -> new BaobabSlabBlock());
	public static final RegistryObject<Block> BAOBAB_FENCE = REGISTRY.register("baobab_fence", () -> new BaobabFenceBlock());
	public static final RegistryObject<Block> BAOBAB_FENCE_GATE = REGISTRY.register("baobab_fence_gate", () -> new BaobabFenceGateBlock());
	public static final RegistryObject<Block> BAOBAB_PRESSURE_PLATE = REGISTRY.register("baobab_pressure_plate", () -> new BaobabPressurePlateBlock());
	public static final RegistryObject<Block> BAOBAB_BUTTON = REGISTRY.register("baobab_button", () -> new BaobabButtonBlock());
	public static final RegistryObject<Block> CACTUS_WOOD = REGISTRY.register("cactus_wood", () -> new CactusWoodBlock());
	public static final RegistryObject<Block> CACTUS_LOG = REGISTRY.register("cactus_log", () -> new CactusLogBlock());
	public static final RegistryObject<Block> CACTUS_PLANKS = REGISTRY.register("cactus_planks", () -> new CactusPlanksBlock());
	public static final RegistryObject<Block> CACTUS_STAIRS = REGISTRY.register("cactus_stairs", () -> new CactusStairsBlock());
	public static final RegistryObject<Block> CACTUS_SLAB = REGISTRY.register("cactus_slab", () -> new CactusSlabBlock());
	public static final RegistryObject<Block> CACTUS_FENCE = REGISTRY.register("cactus_fence", () -> new CactusFenceBlock());
	public static final RegistryObject<Block> CACTUS_FENCE_GATE = REGISTRY.register("cactus_fence_gate", () -> new CactusFenceGateBlock());
	public static final RegistryObject<Block> CACTUS_PRESSURE_PLATE = REGISTRY.register("cactus_pressure_plate", () -> new CactusPressurePlateBlock());
	public static final RegistryObject<Block> CACTUS_BUTTON = REGISTRY.register("cactus_button", () -> new CactusButtonBlock());
	public static final RegistryObject<Block> MAHOGANY_WOOD = REGISTRY.register("mahogany_wood", () -> new MahoganyWoodBlock());
	public static final RegistryObject<Block> MAHOGANY_LOG = REGISTRY.register("mahogany_log", () -> new MahoganyLogBlock());
	public static final RegistryObject<Block> MAHOGANY_PLANKS = REGISTRY.register("mahogany_planks", () -> new MahoganyPlanksBlock());
	public static final RegistryObject<Block> MAHOGANY_STAIRS = REGISTRY.register("mahogany_stairs", () -> new MahoganyStairsBlock());
	public static final RegistryObject<Block> MAHOGANY_SLAB = REGISTRY.register("mahogany_slab", () -> new MahoganySlabBlock());
	public static final RegistryObject<Block> MAHOGANY_FENCE = REGISTRY.register("mahogany_fence", () -> new MahoganyFenceBlock());
	public static final RegistryObject<Block> MAHOGANY_FENCE_GATE = REGISTRY.register("mahogany_fence_gate", () -> new MahoganyFenceGateBlock());
	public static final RegistryObject<Block> MAHOGANY_PRESSURE_PLATE = REGISTRY.register("mahogany_pressure_plate", () -> new MahoganyPressurePlateBlock());
	public static final RegistryObject<Block> MAHOGANY_BUTTON = REGISTRY.register("mahogany_button", () -> new MahoganyButtonBlock());
	public static final RegistryObject<Block> TEAK_WOOD = REGISTRY.register("teak_wood", () -> new TeakWoodBlock());
	public static final RegistryObject<Block> TEAK_LOG = REGISTRY.register("teak_log", () -> new TeakLogBlock());
	public static final RegistryObject<Block> TEAK_PLANKS = REGISTRY.register("teak_planks", () -> new TeakPlanksBlock());
	public static final RegistryObject<Block> TEAK_STAIRS = REGISTRY.register("teak_stairs", () -> new TeakStairsBlock());
	public static final RegistryObject<Block> TEAK_SLAB = REGISTRY.register("teak_slab", () -> new TeakSlabBlock());
	public static final RegistryObject<Block> TEAK_FENCE = REGISTRY.register("teak_fence", () -> new TeakFenceBlock());
	public static final RegistryObject<Block> TEAK_FENCE_GATE = REGISTRY.register("teak_fence_gate", () -> new TeakFenceGateBlock());
	public static final RegistryObject<Block> TEAK_PRESSURE_PLATE = REGISTRY.register("teak_pressure_plate", () -> new TeakPressurePlateBlock());
	public static final RegistryObject<Block> TEAK_BUTTON = REGISTRY.register("teak_button", () -> new TeakButtonBlock());
	public static final RegistryObject<Block> KAPOK_WOOD = REGISTRY.register("kapok_wood", () -> new KapokWoodBlock());
	public static final RegistryObject<Block> KAPOK_LOG = REGISTRY.register("kapok_log", () -> new KapokLogBlock());
	public static final RegistryObject<Block> KAPOK_PLANKS = REGISTRY.register("kapok_planks", () -> new KapokPlanksBlock());
	public static final RegistryObject<Block> KAPOK_STAIRS = REGISTRY.register("kapok_stairs", () -> new KapokStairsBlock());
	public static final RegistryObject<Block> KAPOK_SLAB = REGISTRY.register("kapok_slab", () -> new KapokSlabBlock());
	public static final RegistryObject<Block> KAPOK_FENCE = REGISTRY.register("kapok_fence", () -> new KapokFenceBlock());
	public static final RegistryObject<Block> KAPOK_FENCE_GATE = REGISTRY.register("kapok_fence_gate", () -> new KapokFenceGateBlock());
	public static final RegistryObject<Block> KAPOK_PRESSURE_PLATE = REGISTRY.register("kapok_pressure_plate", () -> new KapokPressurePlateBlock());
	public static final RegistryObject<Block> KAPOK_BUTTON = REGISTRY.register("kapok_button", () -> new KapokButtonBlock());
	public static final RegistryObject<Block> MAPLE_LEAVES = REGISTRY.register("maple_leaves", () -> new MapleLeavesBlock());
	public static final RegistryObject<Block> PINE_LEAVES = REGISTRY.register("pine_leaves", () -> new PineLeavesBlock());
	public static final RegistryObject<Block> CEDAR_LEAVES = REGISTRY.register("cedar_leaves", () -> new CedarLeavesBlock());
	public static final RegistryObject<Block> PALM_LEAVES = REGISTRY.register("palm_leaves", () -> new PalmLeavesBlock());
	public static final RegistryObject<Block> MANGO_LEAVES = REGISTRY.register("mango_leaves", () -> new MangoLeavesBlock());
	public static final RegistryObject<Block> RUBBER_LEAVES = REGISTRY.register("rubber_leaves", () -> new RubberLeavesBlock());
	public static final RegistryObject<Block> BEECH_LEAVES = REGISTRY.register("beech_leaves", () -> new BeechLeavesBlock());
	public static final RegistryObject<Block> WILLOW_LEAVES = REGISTRY.register("willow_leaves", () -> new WillowLeavesBlock());
	public static final RegistryObject<Block> ASPEN_LEAVES = REGISTRY.register("aspen_leaves", () -> new AspenLeavesBlock());
	public static final RegistryObject<Block> JOSHUA_LEAVES = REGISTRY.register("joshua_leaves", () -> new JoshuaLeavesBlock());
	public static final RegistryObject<Block> BAOBAB_LEAVES = REGISTRY.register("baobab_leaves", () -> new BaobabLeavesBlock());
	public static final RegistryObject<Block> CACTUS_LEAVES = REGISTRY.register("cactus_leaves", () -> new CactusLeavesBlock());
	public static final RegistryObject<Block> MAHOGANY_LEAVES = REGISTRY.register("mahogany_leaves", () -> new MahoganyLeavesBlock());
	public static final RegistryObject<Block> TEAK_LEAVES = REGISTRY.register("teak_leaves", () -> new TeakLeavesBlock());
	public static final RegistryObject<Block> KAPOK_LEAVES = REGISTRY.register("kapok_leaves", () -> new KapokLeavesBlock());
	public static final RegistryObject<Block> MAPLE_FALL_LEAVES = REGISTRY.register("maple_fall_leaves", () -> new MapleFallLeavesBlock());
	public static final RegistryObject<Block> BEECH_FALL_LEAVES = REGISTRY.register("beech_fall_leaves", () -> new BeechFallLeavesBlock());
	public static final RegistryObject<Block> ASPEN_FALL_LEAVES = REGISTRY.register("aspen_fall_leaves", () -> new AspenFallLeavesBlock());
	public static final RegistryObject<Block> WOODWORKER = REGISTRY.register("woodworker", () -> new WoodworkerBlock());
}
