
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.officiallysp.woodworks.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import com.officiallysp.woodworks.item.MangoItem;
import com.officiallysp.woodworks.WoodworksMod;

public class WoodworksModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, WoodworksMod.MODID);
	public static final RegistryObject<Item> MAPLE_LOG = block(WoodworksModBlocks.MAPLE_LOG);
	public static final RegistryObject<Item> MAPLE_WOOD = block(WoodworksModBlocks.MAPLE_WOOD);
	public static final RegistryObject<Item> MAPLE_PLANKS = block(WoodworksModBlocks.MAPLE_PLANKS);
	public static final RegistryObject<Item> MAPLE_LEAVES = block(WoodworksModBlocks.MAPLE_LEAVES);
	public static final RegistryObject<Item> MAPLE_STAIRS = block(WoodworksModBlocks.MAPLE_STAIRS);
	public static final RegistryObject<Item> MAPLE_SLAB = block(WoodworksModBlocks.MAPLE_SLAB);
	public static final RegistryObject<Item> MAPLE_FENCE = block(WoodworksModBlocks.MAPLE_FENCE);
	public static final RegistryObject<Item> MAPLE_FENCE_GATE = block(WoodworksModBlocks.MAPLE_FENCE_GATE);
	public static final RegistryObject<Item> MAPLE_PRESSURE_PLATE = block(WoodworksModBlocks.MAPLE_PRESSURE_PLATE);
	public static final RegistryObject<Item> MAPLE_BUTTON = block(WoodworksModBlocks.MAPLE_BUTTON);
	public static final RegistryObject<Item> PINE_WOOD = block(WoodworksModBlocks.PINE_WOOD);
	public static final RegistryObject<Item> PINE_LOG = block(WoodworksModBlocks.PINE_LOG);
	public static final RegistryObject<Item> PINE_PLANKS = block(WoodworksModBlocks.PINE_PLANKS);
	public static final RegistryObject<Item> PINE_LEAVES = block(WoodworksModBlocks.PINE_LEAVES);
	public static final RegistryObject<Item> PINE_STAIRS = block(WoodworksModBlocks.PINE_STAIRS);
	public static final RegistryObject<Item> PINE_SLAB = block(WoodworksModBlocks.PINE_SLAB);
	public static final RegistryObject<Item> PINE_FENCE = block(WoodworksModBlocks.PINE_FENCE);
	public static final RegistryObject<Item> PINE_FENCE_GATE = block(WoodworksModBlocks.PINE_FENCE_GATE);
	public static final RegistryObject<Item> PINE_PRESSURE_PLATE = block(WoodworksModBlocks.PINE_PRESSURE_PLATE);
	public static final RegistryObject<Item> PINE_BUTTON = block(WoodworksModBlocks.PINE_BUTTON);
	public static final RegistryObject<Item> CEDAR_WOOD = block(WoodworksModBlocks.CEDAR_WOOD);
	public static final RegistryObject<Item> CEDAR_LOG = block(WoodworksModBlocks.CEDAR_LOG);
	public static final RegistryObject<Item> CEDAR_PLANKS = block(WoodworksModBlocks.CEDAR_PLANKS);
	public static final RegistryObject<Item> CEDAR_LEAVES = block(WoodworksModBlocks.CEDAR_LEAVES);
	public static final RegistryObject<Item> CEDAR_STAIRS = block(WoodworksModBlocks.CEDAR_STAIRS);
	public static final RegistryObject<Item> CEDAR_SLAB = block(WoodworksModBlocks.CEDAR_SLAB);
	public static final RegistryObject<Item> CEDAR_FENCE = block(WoodworksModBlocks.CEDAR_FENCE);
	public static final RegistryObject<Item> CEDAR_FENCE_GATE = block(WoodworksModBlocks.CEDAR_FENCE_GATE);
	public static final RegistryObject<Item> CEDAR_PRESSURE_PLATE = block(WoodworksModBlocks.CEDAR_PRESSURE_PLATE);
	public static final RegistryObject<Item> CEDAR_BUTTON = block(WoodworksModBlocks.CEDAR_BUTTON);
	public static final RegistryObject<Item> PALM_WOOD = block(WoodworksModBlocks.PALM_WOOD);
	public static final RegistryObject<Item> PALM_LOG = block(WoodworksModBlocks.PALM_LOG);
	public static final RegistryObject<Item> PALM_PLANKS = block(WoodworksModBlocks.PALM_PLANKS);
	public static final RegistryObject<Item> PALM_LEAVES = block(WoodworksModBlocks.PALM_LEAVES);
	public static final RegistryObject<Item> PALM_STAIRS = block(WoodworksModBlocks.PALM_STAIRS);
	public static final RegistryObject<Item> PALM_SLAB = block(WoodworksModBlocks.PALM_SLAB);
	public static final RegistryObject<Item> PALM_FENCE = block(WoodworksModBlocks.PALM_FENCE);
	public static final RegistryObject<Item> PALM_FENCE_GATE = block(WoodworksModBlocks.PALM_FENCE_GATE);
	public static final RegistryObject<Item> PALM_PRESSURE_PLATE = block(WoodworksModBlocks.PALM_PRESSURE_PLATE);
	public static final RegistryObject<Item> PALM_BUTTON = block(WoodworksModBlocks.PALM_BUTTON);
	public static final RegistryObject<Item> MANGO_WOOD = block(WoodworksModBlocks.MANGO_WOOD);
	public static final RegistryObject<Item> MANGO_LOG = block(WoodworksModBlocks.MANGO_LOG);
	public static final RegistryObject<Item> MANGO_PLANKS = block(WoodworksModBlocks.MANGO_PLANKS);
	public static final RegistryObject<Item> MANGO_LEAVES = block(WoodworksModBlocks.MANGO_LEAVES);
	public static final RegistryObject<Item> MANGO_STAIRS = block(WoodworksModBlocks.MANGO_STAIRS);
	public static final RegistryObject<Item> MANGO_SLAB = block(WoodworksModBlocks.MANGO_SLAB);
	public static final RegistryObject<Item> MANGO_FENCE = block(WoodworksModBlocks.MANGO_FENCE);
	public static final RegistryObject<Item> MANGO_FENCE_GATE = block(WoodworksModBlocks.MANGO_FENCE_GATE);
	public static final RegistryObject<Item> MANGO_PRESSURE_PLATE = block(WoodworksModBlocks.MANGO_PRESSURE_PLATE);
	public static final RegistryObject<Item> MANGO_BUTTON = block(WoodworksModBlocks.MANGO_BUTTON);
	public static final RegistryObject<Item> RUBBER_WOOD = block(WoodworksModBlocks.RUBBER_WOOD);
	public static final RegistryObject<Item> RUBBER_LOG = block(WoodworksModBlocks.RUBBER_LOG);
	public static final RegistryObject<Item> RUBBER_PLANKS = block(WoodworksModBlocks.RUBBER_PLANKS);
	public static final RegistryObject<Item> RUBBER_LEAVES = block(WoodworksModBlocks.RUBBER_LEAVES);
	public static final RegistryObject<Item> RUBBER_STAIRS = block(WoodworksModBlocks.RUBBER_STAIRS);
	public static final RegistryObject<Item> RUBBER_SLAB = block(WoodworksModBlocks.RUBBER_SLAB);
	public static final RegistryObject<Item> RUBBER_FENCE = block(WoodworksModBlocks.RUBBER_FENCE);
	public static final RegistryObject<Item> RUBBER_FENCE_GATE = block(WoodworksModBlocks.RUBBER_FENCE_GATE);
	public static final RegistryObject<Item> RUBBER_PRESSURE_PLATE = block(WoodworksModBlocks.RUBBER_PRESSURE_PLATE);
	public static final RegistryObject<Item> RUBBER_BUTTON = block(WoodworksModBlocks.RUBBER_BUTTON);
	public static final RegistryObject<Item> MANGO = REGISTRY.register("mango", () -> new MangoItem());
	public static final RegistryObject<Item> BEECH_WOOD = block(WoodworksModBlocks.BEECH_WOOD);
	public static final RegistryObject<Item> BEECH_LOG = block(WoodworksModBlocks.BEECH_LOG);
	public static final RegistryObject<Item> BEECH_PLANKS = block(WoodworksModBlocks.BEECH_PLANKS);
	public static final RegistryObject<Item> BEECH_LEAVES = block(WoodworksModBlocks.BEECH_LEAVES);
	public static final RegistryObject<Item> BEECH_STAIRS = block(WoodworksModBlocks.BEECH_STAIRS);
	public static final RegistryObject<Item> BEECH_SLAB = block(WoodworksModBlocks.BEECH_SLAB);
	public static final RegistryObject<Item> BEECH_FENCE = block(WoodworksModBlocks.BEECH_FENCE);
	public static final RegistryObject<Item> BEECH_FENCE_GATE = block(WoodworksModBlocks.BEECH_FENCE_GATE);
	public static final RegistryObject<Item> BEECH_PRESSURE_PLATE = block(WoodworksModBlocks.BEECH_PRESSURE_PLATE);
	public static final RegistryObject<Item> BEECH_BUTTON = block(WoodworksModBlocks.BEECH_BUTTON);
	public static final RegistryObject<Item> WILLOW_WOOD = block(WoodworksModBlocks.WILLOW_WOOD);
	public static final RegistryObject<Item> WILLOW_LOG = block(WoodworksModBlocks.WILLOW_LOG);
	public static final RegistryObject<Item> WILLOW_PLANKS = block(WoodworksModBlocks.WILLOW_PLANKS);
	public static final RegistryObject<Item> WILLOW_LEAVES = block(WoodworksModBlocks.WILLOW_LEAVES);
	public static final RegistryObject<Item> WILLOW_STAIRS = block(WoodworksModBlocks.WILLOW_STAIRS);
	public static final RegistryObject<Item> WILLOW_SLAB = block(WoodworksModBlocks.WILLOW_SLAB);
	public static final RegistryObject<Item> WILLOW_FENCE = block(WoodworksModBlocks.WILLOW_FENCE);
	public static final RegistryObject<Item> WILLOW_FENCE_GATE = block(WoodworksModBlocks.WILLOW_FENCE_GATE);
	public static final RegistryObject<Item> WILLOW_PRESSURE_PLATE = block(WoodworksModBlocks.WILLOW_PRESSURE_PLATE);
	public static final RegistryObject<Item> WILLOW_BUTTON = block(WoodworksModBlocks.WILLOW_BUTTON);
	public static final RegistryObject<Item> ASPEN_WOOD = block(WoodworksModBlocks.ASPEN_WOOD);
	public static final RegistryObject<Item> ASPEN_LOG = block(WoodworksModBlocks.ASPEN_LOG);
	public static final RegistryObject<Item> ASPEN_PLANKS = block(WoodworksModBlocks.ASPEN_PLANKS);
	public static final RegistryObject<Item> ASPEN_LEAVES = block(WoodworksModBlocks.ASPEN_LEAVES);
	public static final RegistryObject<Item> ASPEN_STAIRS = block(WoodworksModBlocks.ASPEN_STAIRS);
	public static final RegistryObject<Item> ASPEN_SLAB = block(WoodworksModBlocks.ASPEN_SLAB);
	public static final RegistryObject<Item> ASPEN_FENCE = block(WoodworksModBlocks.ASPEN_FENCE);
	public static final RegistryObject<Item> ASPEN_FENCE_GATE = block(WoodworksModBlocks.ASPEN_FENCE_GATE);
	public static final RegistryObject<Item> ASPEN_PRESSURE_PLATE = block(WoodworksModBlocks.ASPEN_PRESSURE_PLATE);
	public static final RegistryObject<Item> ASPEN_BUTTON = block(WoodworksModBlocks.ASPEN_BUTTON);
	public static final RegistryObject<Item> JOSHUA_WOOD = block(WoodworksModBlocks.JOSHUA_WOOD);
	public static final RegistryObject<Item> JOSHUA_LOG = block(WoodworksModBlocks.JOSHUA_LOG);
	public static final RegistryObject<Item> JOSHUA_PLANKS = block(WoodworksModBlocks.JOSHUA_PLANKS);
	public static final RegistryObject<Item> JOSHUA_LEAVES = block(WoodworksModBlocks.JOSHUA_LEAVES);
	public static final RegistryObject<Item> JOSHUA_STAIRS = block(WoodworksModBlocks.JOSHUA_STAIRS);
	public static final RegistryObject<Item> JOSHUA_SLAB = block(WoodworksModBlocks.JOSHUA_SLAB);
	public static final RegistryObject<Item> JOSHUA_FENCE = block(WoodworksModBlocks.JOSHUA_FENCE);
	public static final RegistryObject<Item> JOSHUA_FENCE_GATE = block(WoodworksModBlocks.JOSHUA_FENCE_GATE);
	public static final RegistryObject<Item> JOSHUA_PRESSURE_PLATE = block(WoodworksModBlocks.JOSHUA_PRESSURE_PLATE);
	public static final RegistryObject<Item> JOSHUA_BUTTON = block(WoodworksModBlocks.JOSHUA_BUTTON);
	public static final RegistryObject<Item> BAOBAB_WOOD = block(WoodworksModBlocks.BAOBAB_WOOD);
	public static final RegistryObject<Item> BAOBAB_LOG = block(WoodworksModBlocks.BAOBAB_LOG);
	public static final RegistryObject<Item> BAOBAB_PLANKS = block(WoodworksModBlocks.BAOBAB_PLANKS);
	public static final RegistryObject<Item> BAOBAB_LEAVES = block(WoodworksModBlocks.BAOBAB_LEAVES);
	public static final RegistryObject<Item> BAOBAB_STAIRS = block(WoodworksModBlocks.BAOBAB_STAIRS);
	public static final RegistryObject<Item> BAOBAB_SLAB = block(WoodworksModBlocks.BAOBAB_SLAB);
	public static final RegistryObject<Item> BAOBAB_FENCE = block(WoodworksModBlocks.BAOBAB_FENCE);
	public static final RegistryObject<Item> BAOBAB_FENCE_GATE = block(WoodworksModBlocks.BAOBAB_FENCE_GATE);
	public static final RegistryObject<Item> BAOBAB_PRESSURE_PLATE = block(WoodworksModBlocks.BAOBAB_PRESSURE_PLATE);
	public static final RegistryObject<Item> BAOBAB_BUTTON = block(WoodworksModBlocks.BAOBAB_BUTTON);
	public static final RegistryObject<Item> CACTUS_WOOD = block(WoodworksModBlocks.CACTUS_WOOD);
	public static final RegistryObject<Item> CACTUS_LOG = block(WoodworksModBlocks.CACTUS_LOG);
	public static final RegistryObject<Item> CACTUS_PLANKS = block(WoodworksModBlocks.CACTUS_PLANKS);
	public static final RegistryObject<Item> CACTUS_LEAVES = block(WoodworksModBlocks.CACTUS_LEAVES);
	public static final RegistryObject<Item> CACTUS_STAIRS = block(WoodworksModBlocks.CACTUS_STAIRS);
	public static final RegistryObject<Item> CACTUS_SLAB = block(WoodworksModBlocks.CACTUS_SLAB);
	public static final RegistryObject<Item> CACTUS_FENCE = block(WoodworksModBlocks.CACTUS_FENCE);
	public static final RegistryObject<Item> CACTUS_FENCE_GATE = block(WoodworksModBlocks.CACTUS_FENCE_GATE);
	public static final RegistryObject<Item> CACTUS_PRESSURE_PLATE = block(WoodworksModBlocks.CACTUS_PRESSURE_PLATE);
	public static final RegistryObject<Item> CACTUS_BUTTON = block(WoodworksModBlocks.CACTUS_BUTTON);
	public static final RegistryObject<Item> MAHOGANY_WOOD = block(WoodworksModBlocks.MAHOGANY_WOOD);
	public static final RegistryObject<Item> MAHOGANY_LOG = block(WoodworksModBlocks.MAHOGANY_LOG);
	public static final RegistryObject<Item> MAHOGANY_PLANKS = block(WoodworksModBlocks.MAHOGANY_PLANKS);
	public static final RegistryObject<Item> MAHOGANY_LEAVES = block(WoodworksModBlocks.MAHOGANY_LEAVES);
	public static final RegistryObject<Item> MAHOGANY_STAIRS = block(WoodworksModBlocks.MAHOGANY_STAIRS);
	public static final RegistryObject<Item> MAHOGANY_SLAB = block(WoodworksModBlocks.MAHOGANY_SLAB);
	public static final RegistryObject<Item> MAHOGANY_FENCE = block(WoodworksModBlocks.MAHOGANY_FENCE);
	public static final RegistryObject<Item> MAHOGANY_FENCE_GATE = block(WoodworksModBlocks.MAHOGANY_FENCE_GATE);
	public static final RegistryObject<Item> MAHOGANY_PRESSURE_PLATE = block(WoodworksModBlocks.MAHOGANY_PRESSURE_PLATE);
	public static final RegistryObject<Item> MAHOGANY_BUTTON = block(WoodworksModBlocks.MAHOGANY_BUTTON);
	public static final RegistryObject<Item> TEAK_WOOD = block(WoodworksModBlocks.TEAK_WOOD);
	public static final RegistryObject<Item> TEAK_LOG = block(WoodworksModBlocks.TEAK_LOG);
	public static final RegistryObject<Item> TEAK_PLANKS = block(WoodworksModBlocks.TEAK_PLANKS);
	public static final RegistryObject<Item> TEAK_LEAVES = block(WoodworksModBlocks.TEAK_LEAVES);
	public static final RegistryObject<Item> TEAK_STAIRS = block(WoodworksModBlocks.TEAK_STAIRS);
	public static final RegistryObject<Item> TEAK_SLAB = block(WoodworksModBlocks.TEAK_SLAB);
	public static final RegistryObject<Item> TEAK_FENCE = block(WoodworksModBlocks.TEAK_FENCE);
	public static final RegistryObject<Item> TEAK_FENCE_GATE = block(WoodworksModBlocks.TEAK_FENCE_GATE);
	public static final RegistryObject<Item> TEAK_PRESSURE_PLATE = block(WoodworksModBlocks.TEAK_PRESSURE_PLATE);
	public static final RegistryObject<Item> TEAK_BUTTON = block(WoodworksModBlocks.TEAK_BUTTON);
	public static final RegistryObject<Item> KAPOK_WOOD = block(WoodworksModBlocks.KAPOK_WOOD);
	public static final RegistryObject<Item> KAPOK_LOG = block(WoodworksModBlocks.KAPOK_LOG);
	public static final RegistryObject<Item> KAPOK_PLANKS = block(WoodworksModBlocks.KAPOK_PLANKS);
	public static final RegistryObject<Item> KAPOK_LEAVES = block(WoodworksModBlocks.KAPOK_LEAVES);
	public static final RegistryObject<Item> KAPOK_STAIRS = block(WoodworksModBlocks.KAPOK_STAIRS);
	public static final RegistryObject<Item> KAPOK_SLAB = block(WoodworksModBlocks.KAPOK_SLAB);
	public static final RegistryObject<Item> KAPOK_FENCE = block(WoodworksModBlocks.KAPOK_FENCE);
	public static final RegistryObject<Item> KAPOK_FENCE_GATE = block(WoodworksModBlocks.KAPOK_FENCE_GATE);
	public static final RegistryObject<Item> KAPOK_PRESSURE_PLATE = block(WoodworksModBlocks.KAPOK_PRESSURE_PLATE);
	public static final RegistryObject<Item> KAPOK_BUTTON = block(WoodworksModBlocks.KAPOK_BUTTON);
	public static final RegistryObject<Item> MAPLE_FALL_LEAVES = block(WoodworksModBlocks.MAPLE_FALL_LEAVES);
	public static final RegistryObject<Item> WOODWORKER = block(WoodworksModBlocks.WOODWORKER);
	public static final RegistryObject<Item> BEECH_FALL_LEAVES = block(WoodworksModBlocks.BEECH_FALL_LEAVES);
	public static final RegistryObject<Item> ASPEN_FALL_LEAVES = block(WoodworksModBlocks.ASPEN_FALL_LEAVES);
	public static final RegistryObject<Item> STRIPPED_WILLOW_WOOD = block(WoodworksModBlocks.STRIPPED_WILLOW_WOOD);
	public static final RegistryObject<Item> STRIPPED_WILLOW_LOG = block(WoodworksModBlocks.STRIPPED_WILLOW_LOG);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
